# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ios-template' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-template

  # Network
  pod 'Alamofire', '~> 5.4'
  pod 'ReachabilitySwift'

  # Layout
  pod 'SnapKit', '~> 5.0.0'

  # Utilities
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  
end
